// Fantasy ジャンル拡張バッチ3: fantasy_101～fantasy_170
// 小説・文学作品のみ、漫画除外

export const fantasyExpansionBatch3 = [
  // Beginner Practical (初心者・実用的) - 入門向けファンタジー
  {
    id: 'fantasy_101',
    title: 'スター・ウォーズ エピソード4 新たなる希望',
    author: 'ジョージ・ルーカス',
    description: '遠い昔、はるか彼方の銀河系で繰り広げられる、光と闇の戦い。',
    asin: '4047913995',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'space_opera', 'good_vs_evil', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_102',
    title: 'E.T.',
    author: 'ウィリアム・コッツウィンクル',
    description: '地球に取り残された宇宙人E.T.と少年エリオットの心温まる交流。',
    asin: '4048730908',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'alien_friendship', 'family', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_103',
    title: 'バック・トゥ・ザ・フューチャー',
    author: 'ジョージ・ゲイプス',
    description: 'タイムマシンで過去に戻った高校生マーティの冒険。',
    asin: '4087030067',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'time_travel', 'adventure', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_104',
    title: 'ゴーストバスターズ',
    author: 'ラリー・ミルン',
    description: 'ニューヨークに現れた幽霊たちを退治する、ゴーストバスターズの活躍。',
    asin: '4087030083',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'ghost_hunting', 'comedy', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_105',
    title: 'ジュマンジ',
    author: 'クリス・ヴァン・オールズバーグ',
    description: 'ボードゲームの世界が現実になる、スリルと冒険の物語。',
    asin: '4378001181',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'board_game', 'adventure', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_106',
    title: 'フック',
    author: 'テリー・ブルックス',
    description: '大人になったピーター・パンが、再びネバーランドで冒険する。',
    asin: '4087031705',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'peter_pan', 'adult_return', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_107',
    title: 'ラビリンス 魔王の迷宮',
    author: 'A.C.H.スミス',
    description: '赤ちゃんの弟を魔王に奪われた少女サラの、迷宮での冒険。',
    asin: '4087032094',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'labyrinth', 'rescue_mission', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_108',
    title: 'グレムリン',
    author: 'ジョージ・ガイプ',
    description: '不思議な生き物モグワイが、水に濡れると恐ろしいグレムリンに変身。',
    asin: '4087030121',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'creature_feature', 'horror_comedy', 'foreign'],
    rating: 4.1,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_109',
    title: 'コクーン',
    author: 'デイヴィッド・サパースタイン',
    description: '宇宙人の技術で若返った老人たちの、第二の人生。',
    asin: '4087031292',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'aging', 'aliens', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_110',
    title: 'ショート・サーキット',
    author: 'S.S.ウィルソン',
    description: '雷に打たれて感情を持ったロボット「ナンバー5」の冒険。',
    asin: '4087030156',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_practical', 'robot_ai', 'comedy', 'foreign'],
    rating: 4.0,
    genre: 'fantasy'
  },

  // Beginner Theoretical (初心者・理論的) - SF理論入門
  {
    id: 'fantasy_111',
    title: 'タイム・マシン',
    author: 'H.G.ウェルズ',
    description: '時間旅行を発明した科学者が見た、人類の未来。SF小説の古典。',
    asin: '4102145028',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'time_travel', 'social_evolution', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_112',
    title: '宇宙戦争',
    author: 'H.G.ウェルズ',
    description: '火星人による地球侵略を描いた、SFの原点とも言える作品。',
    asin: '4102145036',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'alien_invasion', 'survival', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_113',
    title: '海底二万里',
    author: 'ジュール・ヴェルヌ',
    description: '謎の潜水艦ノーチラス号での、海底世界の冒険。',
    asin: '4102112014',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'underwater', 'exploration', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_114',
    title: '月世界旅行',
    author: 'ジュール・ヴェルヌ',
    description: '大砲で月へと向かう、宇宙旅行の先駆的作品。',
    asin: '4102112022',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'moon_travel', 'space_exploration', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_115',
    title: '透明人間',
    author: 'H.G.ウェルズ',
    description: '透明化実験に成功した科学者の狂気と破滅。',
    asin: '4102145044',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'invisibility', 'mad_scientist', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_116',
    title: 'ドクター・ジキルとハイド氏',
    author: 'ロバート・L・スティーヴンソン',
    description: '善と悪の二重人格を描いた、心理的ホラーの名作。',
    asin: '4102130012',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'dual_personality', 'psychology', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_117',
    title: 'フランケンシュタイン',
    author: 'メアリー・シェリー',
    description: '科学によって作られた人造人間と創造主の悲劇。',
    asin: '4102130020',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'artificial_life', 'creation_ethics', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_118',
    title: '中国の人形',
    author: 'ロバート・ヴァン・ヒューリック',
    description: '古代中国を舞台にした、ディー判事の謎解き。',
    asin: '4151200541',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'ancient_china', 'detective', 'foreign'],
    rating: 4.1,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_119',
    title: '失われた世界',
    author: 'アーサー・コナン・ドイル',
    description: '南米の秘境で恐竜が生きている世界を発見した探検隊の冒険。',
    asin: '4102134018',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'lost_world', 'dinosaurs', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_120',
    title: '毒ガス帯',
    author: 'アーサー・コナン・ドイル',
    description: '地球を覆う毒ガス帯によって人類が危機に瀕する。',
    asin: '4102134026',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_theoretical', 'environmental_disaster', 'survival', 'foreign'],
    rating: 4.0,
    genre: 'fantasy'
  },

  // Beginner Inspirational (初心者・感動的) - 心温まるファンタジー
  {
    id: 'fantasy_121',
    title: 'リトル・プリンス 星の王子さま',
    author: 'サン=テグジュペリ',
    description: '大切なものは目に見えない。心で見るものこそ本当に大切。',
    asin: '4102122044',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'friendship', 'wisdom', 'foreign'],
    rating: 4.8,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_122',
    title: 'アルケミスト 夢を旅した少年',
    author: 'パウロ・コエーリョ',
    description: '夢を追い求める羊飼いの少年の、自分探しの旅。',
    asin: '4041150019',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'self_discovery', 'dreams', 'foreign'],
    rating: 4.6,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_123',
    title: 'かもめのジョナサン',
    author: 'リチャード・バック',
    description: '飛ぶことに情熱を注ぐカモメの、自己実現の物語。',
    asin: '4102036016',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'self_improvement', 'flying', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_124',
    title: 'イリュージョン',
    author: 'リチャード・バック',
    description: '不思議な力を持つ救世主と、彼から学ぶパイロットの物語。',
    asin: '4102036024',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'messiah', 'spiritual_growth', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_125',
    title: 'ライオンと魔女',
    author: 'C.S.ルイス',
    description: 'ナルニア国で繰り広げられる、善と悪の戦い。愛と犠牲の物語。',
    asin: '4001140330',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'sacrifice', 'redemption', 'foreign'],
    rating: 4.7,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_126',
    title: 'カスピアン王子のつのぶえ',
    author: 'C.S.ルイス',
    description: 'ナルニアを取り戻すために戦う、正当な王の物語。',
    asin: '4001140349',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'rightful_king', 'courage', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_127',
    title: '朝びらき丸東の海へ',
    author: 'C.S.ルイス',
    description: 'ナルニアの海を航海し、世界の果てまで旅する冒険。',
    asin: '4001140357',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'sea_voyage', 'exploration', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_128',
    title: '銀のいす',
    author: 'C.S.ルイス',
    description: '行方不明の王子を救うための、地底世界への冒険。',
    asin: '4001140365',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'rescue_mission', 'underground', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_129',
    title: '馬と少年',
    author: 'C.S.ルイス',
    description: 'ナルニアと隣国カロールメンを舞台にした、友情と冒険の物語。',
    asin: '4001140373',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'friendship', 'horses', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_130',
    title: '魔術師のおい',
    author: 'C.S.ルイス',
    description: 'ナルニア国創世の物語。世界がどのように始まったかを描く。',
    asin: '4001140381',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['beginner_inspirational', 'world_creation', 'origins', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },

  // Intermediate Practical (中級・実用的) - 実用的中級ファンタジー
  {
    id: 'fantasy_131',
    title: 'ゲド戦記 こわれた腕環',
    author: 'アーシュラ・K・ル=グウィン',
    description: 'アースシーの墓所で古い墓を暴く者たちと、それを阻止しようとするゲド。',
    asin: '4001109026',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'tomb_raiders', 'magic_balance', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_132',
    title: 'ゲド戦記 さいはての島へ',
    author: 'アーシュラ・K・ル=グウィン',
    description: 'アースシーの魔法が失われていく中、ゲドとアレンの最後の冒険。',
    asin: '4001109034',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'magic_decline', 'mentorship', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_133',
    title: 'ゲド戦記 帰還',
    author: 'アーシュラ・K・ル=グウィン',
    description: '魔法を失ったゲドと、魔法使いを目指す少女テハヌーの物語。',
    asin: '4001109042',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'power_loss', 'female_wizard', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_134',
    title: 'アースシーの風',
    author: 'アーシュラ・K・ル=グウィン',
    description: 'アースシー世界の短編集。様々な島と人々の物語。',
    asin: '4001109050',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'short_stories', 'world_building', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_135',
    title: 'アースシーの炎',
    author: 'アーシュラ・K・ル=グウィン',
    description: 'テハヌーが炎の竜王と出会い、真の魔法使いへと成長する。',
    asin: '4001109069',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'dragon_lord', 'coming_of_age', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_136',
    title: 'ワールドシップ・テープス',
    author: 'ウォルター・ジョン・ウィリアムズ',
    description: '宇宙船で長い旅を続ける人類の、世代を超えた物語。',
    asin: '4150115524',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'generation_ship', 'space_travel', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_137',
    title: 'ニューロマンサー',
    author: 'ウィリアム・ギブスン',
    description: 'サイバースペースに潜るハッカーの、企業に対する反逆。',
    asin: '4150114587',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'cyberpunk', 'hacking', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_138',
    title: 'カウント・ゼロ',
    author: 'ウィリアム・ギブスン',
    description: 'ニューロマンサーの続編。サイバースペースの新たな脅威。',
    asin: '4150114595',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'cyberpunk', 'ai_evolution', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_139',
    title: 'モナリザ・オーヴァドライヴ',
    author: 'ウィリアム・ギブスン',
    description: 'スプロール三部作完結編。仮想現実と現実の境界が曖昧になる。',
    asin: '4150114609',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'virtual_reality', 'identity', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_140',
    title: 'スノウ・クラッシュ',
    author: 'ニール・スティーヴンスン',
    description: 'メタバースでのコンピューターウイルスと現実世界の陰謀。',
    asin: '4150115680',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_practical', 'metaverse', 'computer_virus', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },

  // Intermediate Theoretical (中級・理論的) - 理論的中級ファンタジー
  {
    id: 'fantasy_141',
    title: '都市と星',
    author: 'アーサー・C・クラーク',
    description: '10億年後の地球最後の都市ダイアスパーでの、青年アルヴィンの冒険。',
    asin: '4150114419',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'far_future', 'immortality', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_142',
    title: '地球の長い午後',
    author: 'ブライアン・W・オールディス',
    description: '太陽が膨張した未来の地球で、巨大植物に支配された世界。',
    asin: '4150115397',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'dying_earth', 'plant_evolution', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_143',
    title: 'タウ・ゼロ',
    author: 'ポール・アンダーソン',
    description: '減速できなくなった宇宙船が、宇宙の終わりと始まりを目撃する。',
    asin: '4150115869',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'relativistic_travel', 'cosmology', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_144',
    title: 'リングワールド',
    author: 'ラリイ・ニーヴン',
    description: '恒星を取り巻く巨大な人工リングワールドでの探検。',
    asin: '4150115435',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'megastructure', 'alien_engineering', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_145',
    title: 'レンズマン',
    author: 'エドワード・エルマー・スミス',
    description: '銀河パトロール隊レンズマンの、宇宙規模の善悪の戦い。',
    asin: '4150115281',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'space_opera', 'psychic_powers', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_146',
    title: 'スタープレックス',
    author: 'ロバート・J・ソウヤー',
    description: '異星人と協力して宇宙の謎を探る、宇宙探査船の冒険。',
    asin: '4150116563',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'alien_cooperation', 'space_exploration', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_147',
    title: 'フラッシュフォワード',
    author: 'ロバート・J・ソウヤー',
    description: '全人類が同時に21年後の未来を垣間見る現象の謎。',
    asin: '4150117179',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'future_vision', 'causality', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_148',
    title: 'キャッチワールド',
    author: 'クリス・ボイス',
    description: 'ブラックホールの近くで時間が遅く流れる惑星での生存戦略。',
    asin: '4150116807',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'time_dilation', 'survival', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_149',
    title: 'プシ・マン',
    author: 'アルフレッド・ベスター',
    description: '超能力者たちが支配する未来社会での、権力闘争。',
    asin: '4150115893',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'telepathy', 'psychic_society', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_150',
    title: '虎よ、虎よ！',
    author: 'アルフレッド・ベスター',
    description: '瞬間移動能力を持つ男の復讐劇。サイバーパンクの先駆け。',
    asin: '4150115907',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_theoretical', 'teleportation', 'revenge', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },

  // Intermediate Inspirational (中級・感動的) - 感動的中級ファンタジー
  {
    id: 'fantasy_151',
    title: 'アルジャーノンに花束を',
    author: 'ダニエル・キイス',
    description: '知的障害者が天才になる手術を受けるが、やがて元に戻ってしまう悲劇。',
    asin: '4150114676',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'intelligence', 'human_dignity', 'foreign'],
    rating: 4.8,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_152',
    title: '夏への扉',
    author: 'ロバート・A・ハインライン',
    description: '冷凍睡眠から目覚めた男が、愛猫と共に時間旅行で運命を変える。',
    asin: '4150114684',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'time_travel', 'second_chances', 'foreign'],
    rating: 4.6,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_153',
    title: '月は無慈悲な夜の女王',
    author: 'ロバート・A・ハインライン',
    description: '月世界の植民地が地球からの独立を目指す革命の物語。',
    asin: '4150115400',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'lunar_revolution', 'ai_companion', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_154',
    title: '愛しの座敷わらし',
    author: '荻原浩',
    description: '古い家に住む座敷わらしと家族の心温まる交流。',
    asin: '4065126223',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'zashiki_warashi', 'family', 'japanese'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_155',
    title: '鹿の王',
    author: '上橋菜穂子',
    description: '疫病に立ち向かう元戦士ヴァンと、医術師ホッサルの物語。',
    asin: '4041013461',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'plague', 'healing', 'japanese'],
    rating: 4.7,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_156',
    title: '狐笛のかなた',
    author: '上橋菜穂子',
    description: '妖怪と人間の境界線で生きる少年と、不思議な笛の物語。',
    asin: '4652078382',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'yokai', 'flute_magic', 'japanese'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_157',
    title: '流れ行く者',
    author: '上橋菜穂子',
    description: '異世界を旅する精霊の庭師の物語。短編集。',
    asin: '4652078404',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'spirit_gardener', 'other_worlds', 'japanese'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_158',
    title: '風の又三郎',
    author: '宮沢賢治',
    description: '村にやってきた転校生と子供たちの交流を描いた、幻想的な物語。',
    asin: '4101092079',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'wind_spirit', 'childhood', 'japanese'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_159',
    title: 'セロ弾きのゴーシュ',
    author: '宮沢賢治',
    description: 'チェロの下手な青年ゴーシュが、動物たちとの交流で成長する。',
    asin: '4101092087',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'music', 'animal_teachers', 'japanese'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_160',
    title: 'グスコーブドリの伝記',
    author: '宮沢賢治',
    description: '冷害に苦しむ人々を救うため、自分の命を犠牲にする青年の物語。',
    asin: '4101092095',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['intermediate_inspirational', 'self_sacrifice', 'weather_control', 'japanese'],
    rating: 4.5,
    genre: 'fantasy'
  },

  // Advanced Practical (上級・実用的) - 上級実用ファンタジー
  {
    id: 'fantasy_161',
    title: 'デューン砂の惑星',
    author: 'フランク・ハーバート',
    description: '砂漠の惑星アラキスで繰り広げられる、政治と宗教の壮大な叙事詩。',
    asin: '4150116970',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'desert_planet', 'political_intrigue', 'foreign'],
    rating: 4.7,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_162',
    title: 'デューン砂漠の救世主',
    author: 'フランク・ハーバート',
    description: '皇帝となったポールが直面する、預言者としての苦悩。',
    asin: '4150116989',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'messiah_burden', 'prescience', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_163',
    title: 'デューン砂丘の子供たち',
    author: 'フランク・ハーバート',
    description: 'ポールの子供たちが、父の遺産と運命に立ち向かう。',
    asin: '4150116997',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'legacy_burden', 'transformation', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_164',
    title: '銀河帝国の興亡',
    author: 'アイザック・アシモフ',
    description: '心理歴史学により銀河帝国の崩壊を予測し、文明を保存する計画。',
    asin: '4150116342',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'psychohistory', 'galactic_empire', 'foreign'],
    rating: 4.6,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_165',
    title: 'ファウンデーション対帝国',
    author: 'アイザック・アシモフ',
    description: 'ファウンデーションが帝国と直接対決する危機。',
    asin: '4150116350',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'foundation_crisis', 'mule_mutant', 'foreign'],
    rating: 4.5,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_166',
    title: '第二ファウンデーション',
    author: 'アイザック・アシモフ',
    description: '心理学者たちの秘密組織、第二ファウンデーションの正体。',
    asin: '4150116369',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'second_foundation', 'mental_science', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_167',
    title: 'ファウンデーションの彼方へ',
    author: 'アイザック・アシモフ',
    description: 'ファウンデーション・シリーズ続編。ガイアという惑星意識との出会い。',
    asin: '4150116377',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'gaia_consciousness', 'galactic_unity', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_168',
    title: 'ファウンデーションと地球',
    author: 'アイザック・アシモフ',
    description: '人類の起源である地球を探す旅。銀河の真の歴史。',
    asin: '4150116385',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'earth_origin', 'galactic_history', 'foreign'],
    rating: 4.2,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_169',
    title: 'ファウンデーション序章',
    author: 'アイザック・アシモフ',
    description: '心理歴史学の創始者ハリ・セルダンの若き日の物語。',
    asin: '4150116393',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'seldon_origins', 'psychohistory_birth', 'foreign'],
    rating: 4.3,
    genre: 'fantasy'
  },
  {
    id: 'fantasy_170',
    title: 'ファウンデーション暁',
    author: 'アイザック・アシモフ',
    description: 'セルダンがファウンデーション計画を実行に移すまでの過程。',
    asin: '4150116407',
    amazonUrl: '',
    kindleUrl: '',
    tags: ['advanced_practical', 'foundation_beginning', 'seldon_plan', 'foreign'],
    rating: 4.4,
    genre: 'fantasy'
  }
];